version: '3.8'

services:
  postgresql:
    image: postgres:17.4
    container_name: pg-index-health-postgres
    environment:
      POSTGRES_DB: demo_for_pg_index_health
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: myUniquePassword
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
