name: Java CI

on:
    push:
        branches:
            - master
    pull_request:
    pull_request_target:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                if: ${{ github.event_name != 'pull_request_target' }}
                uses: actions/checkout@v3
            -   name: Checkout PR
                if: ${{ github.event_name == 'pull_request_target' }}
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.event.pull_request.head.sha }}
            -   name: Set up JDK 8
                uses: actions/setup-java@v2
                with:
                    distribution: 'adopt-hotspot'
                    java-version: '8.0'
                    cache: 'gradle'
            -   name: Build with Gradle
                run: ./gradlew build
