name: Lint SQL Migrations

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: Lint SQL Migrations
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v5
                with:
                    # Full git history is needed to get a proper list of changed files within `super-linter`
                    fetch-depth: 0

            -   name: Run SQLFluff
                uses: super-linter/super-linter/slim@v8.2.1
                env:
                    VALIDATE_ALL_CODEBASE: false
                    VALIDATE_SQLFLUFF: true
                    DEFAULT_BRANCH: master
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
