name: Lint Code Base

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: Lint SQL Migrations
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4
                with:
                    # Full git history is needed to get a proper list of changed files within `super-linter`
                    fetch-depth: 0

            -   name: Lint Code Base
                uses: super-linter/super-linter/slim@v7.1.0
                env:
                    VALIDATE_ALL_CODEBASE: false
                    VALIDATE_SQLFLUFF: true
                    DEFAULT_BRANCH: master
                    FILTER_REGEX_INCLUDE: ^db-migrations/src/main/resources/db/changelog/sql/
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
